
development:
  adapter: postgresql
  encoding: unicode
  database: tinyplanet_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: tinyplanet_test
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: tinyplanet_production
  pool: 5

